//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJL_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tx_InventoryReceipt
    {
        public long Id { get; set; }
        public string TransType { get; set; }
        public string TransNo { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string Status { get; set; }
        public string WarehouseCodeFrom { get; set; }
        public string WarehouseNameFrom { get; set; }
        public string WarehouseCodeTo { get; set; }
        public string WarehouseNameTo { get; set; }
        public string ShippingType { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string UnitName { get; set; }
        public Nullable<int> DriverId { get; set; }
        public string DriverName { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> FlowRatePerHour { get; set; }
        public Nullable<System.DateTime> UnloadingStartDate { get; set; }
        public Nullable<System.DateTime> UnloadingStartTime { get; set; }
        public Nullable<System.DateTime> UnloadingEndDate { get; set; }
        public Nullable<System.DateTime> UnloadingEndTime { get; set; }
        public Nullable<int> BinAbsEntry { get; set; }
        public string BinCode { get; set; }
        public Nullable<decimal> FlowMeterReceipt { get; set; }
        public Nullable<decimal> QtyReceipt { get; set; }
        public Nullable<decimal> Deviation { get; set; }
        public Nullable<int> SapDocId { get; set; }
        public string SapDocNo { get; set; }
        public string IsAfterPosted { get; set; }
        public Nullable<int> BinAbsEntryTo { get; set; }
        public string BinCodeTo { get; set; }
        public string BaseTransType { get; set; }
        public Nullable<long> BaseTransId { get; set; }
        public string BaseTransNo { get; set; }
        public Nullable<decimal> QtyTransfer { get; set; }
        public Nullable<decimal> FlowMeterStart { get; set; }
        public Nullable<decimal> FlowMeterEnd { get; set; }
        public Nullable<decimal> Sg { get; set; }
        public Nullable<decimal> Temp { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
        public Nullable<decimal> ActualReceipt { get; set; }
        public Nullable<decimal> MeterFactor { get; set; }
        public Nullable<decimal> QtyAfterMF { get; set; }
    }
}
