//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBS_DI.Models._EF
{
    using System;
    using System.Collections.Generic;
    
<<<<<<<< HEAD:BBS_DI/Models/_EF/Tx_TransferSummaryIn_Item_Tag1.cs
    public partial class Tx_TransferSummaryIn_Item_Tag1
========
    public partial class Tx_TransferSummaryIn_Item_tag
>>>>>>>> c42cb85b4c8da96ee4c24af966d8790aeb01a7b6:BBS_DI/Models/_EF/Tx_TransferSummaryIn_Item_Tag.cs
    {
        public long Id { get; set; }
        public Nullable<long> DetId { get; set; }
        public Nullable<long> DetDetId { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string TagId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string EventType { get; set; }
        public string Status { get; set; }
        public Nullable<long> BaseId { get; set; }
        public Nullable<long> BaseDetId { get; set; }
        public Nullable<long> BaseDetDetId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUser { get; set; }
    }
}
