DROP TABLE "Tx_AdjustmentIn";
CREATE COLUMN TABLE "Tx_AdjustmentIn" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "PostingDate" TIMESTAMP,
    "AdjustmentTypeCode" NVARCHAR(100),
    "AdjustmentTypeName" NVARCHAR(100),    

    "PillarsCode" NVARCHAR(10),
    "PillarsName" NVARCHAR(50),
    "ClassCode" NVARCHAR(10),
    "ClassName" NVARCHAR(50),
    "SubClass1Code" NVARCHAR(10),
    "SubClass1Name" NVARCHAR(50),
    "SubClass2Code" NVARCHAR(10),
    "SubClass2Name" NVARCHAR(50),
    "ProjectCode" NVARCHAR(50),
    "ProjectName" NVARCHAR(100),

    "Status" NVARCHAR(50),
    "IsAfterPosted" CHAR(1),
    "IsOpeningBalance" CHAR(1),
    "DocEntry" INTEGER,
    "Comments" NVARCHAR(200),
    "ScanDeviceId" NVARCHAR(1000),
    "WhsCode" NVARCHAR(50),
    "CancelReason" NVARCHAR(500),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);


DROP TABLE "Tx_AdjustmentIn_Item";
CREATE COLUMN TABLE "Tx_AdjustmentIn_Item" (
    "Id" BIGINT NOT NULL,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "FreeText" NVARCHAR(1000),
    "WhsCode" NVARCHAR(50),

    "PillarsCode" NVARCHAR(10),
    "PillarsName" NVARCHAR(50),
    "ClassCode" NVARCHAR(10),
    "ClassName" NVARCHAR(50),
    "SubClass1Code" NVARCHAR(10),
    "SubClass1Name" NVARCHAR(50),
    "SubClass2Code" NVARCHAR(10),
    "SubClass2Name" NVARCHAR(50),
    "ProjectCode" NVARCHAR(50),
    "ProjectName" NVARCHAR(100),

    "QuantityScan" DECIMAL(21, 2), 
    "QuantityPosted" DECIMAL(21, 2), 
    "LineStatus" NVARCHAR(50),
    "UnitPriceTc" DECIMAL(21, 2),  
    "UomEntry" INT,
    "Uom" NVARCHAR(50),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_AdjustmentIn_Item_Tag";
CREATE COLUMN TABLE "Tx_AdjustmentIn_Item_Tag" (
    "Id" BIGINT,
    "DetId" BIGINT,
    "DetDetId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "TagId" NVARCHAR(200),
    "Quantity" DECIMAL(21,6),
    "EventType" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "PostResultNote" NVARCHAR(500),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_AdjustmentOut";
CREATE COLUMN TABLE "Tx_AdjustmentOut" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "PostingDate" TIMESTAMP,
    "AdjustmentTypeCode" NVARCHAR(100),
    "AdjustmentTypeName" NVARCHAR(100),

    "PillarsCode" NVARCHAR(10),
    "PillarsName" NVARCHAR(50),
    "ClassCode" NVARCHAR(10),
    "ClassName" NVARCHAR(50),
    "SubClass1Code" NVARCHAR(10),
    "SubClass1Name" NVARCHAR(50),
    "SubClass2Code" NVARCHAR(10),
    "SubClass2Name" NVARCHAR(50),
    "ProjectCode" NVARCHAR(50),
    "ProjectName" NVARCHAR(100),

    "Status" NVARCHAR(50),    
    "IsAfterPosted" CHAR(1),
    "IsOpeningBalance" CHAR(1),
    "DocEntry" INTEGER,
    "Comments" NVARCHAR(200),
    "ScanDeviceId" NVARCHAR(1000),
    "WhsCode" NVARCHAR(50),
    "CancelReason" NVARCHAR(500),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_AdjustmentOut_Item";
CREATE COLUMN TABLE "Tx_AdjustmentOut_Item" (
    "Id" BIGINT NOT NULL,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "FreeText" NVARCHAR(1000),
    "WhsCode" NVARCHAR(50),

    "PillarsCode" NVARCHAR(10),
    "PillarsName" NVARCHAR(50),
    "ClassCode" NVARCHAR(10),
    "ClassName" NVARCHAR(50),
    "SubClass1Code" NVARCHAR(10),
    "SubClass1Name" NVARCHAR(50),
    "SubClass2Code" NVARCHAR(10),
    "SubClass2Name" NVARCHAR(50),
    "ProjectCode" NVARCHAR(50),
    "ProjectName" NVARCHAR(100),

    "QuantityScan" DECIMAL(21, 2),
    "QuantityPosted" DECIMAL(21, 2), 
    "LineStatus" NVARCHAR(50),
    "UomEntry" INT,
    "Uom" NVARCHAR(50),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_AdjustmentOut_Item_Tag";
CREATE COLUMN TABLE "Tx_AdjustmentOut_Item_Tag" (
    "Id" BIGINT,
    "DetId" BIGINT,
    "DetDetId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "TagId" NVARCHAR(200),
    "Quantity" DECIMAL(21,6),
    "EventType" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "PostResultNote" NVARCHAR(500),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_PurchaseOrder";
CREATE COLUMN TABLE ""Tx_PurchaseOrder" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "VendorCode" NVARCHAR(50),
    "VendorName" VARCHAR(100),
    "Address" NVARCHAR(254),
    "DocEntry" BIGINT,
    "DocNum" NVARCHAR(50),
    "DocDate" TIMESTAMP,
    "RefNo" NVARCHAR(100),
    "ScanDeviceId" NVARCHAR(1000),
    "Status" NVARCHAR(50),
    "IsAfterPosted" CHAR(1),
    "Comments" NVARCHAR(254),
    "CancelReason" NVARCHAR(254),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER,
    PRIMARY KEY ("Id")
);

DROP TABLE "Tx_PurchaseOrder_Item";
CREATE COLUMN TABLE "Tx_PurchaseOrder_Item" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "DocEntry" BIGINT,
    "DocNum" NVARCHAR(50),
    "BaseLine" INTEGER,
    "LineNum" INTEGER,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "WhsCode" NVARCHAR(50),
    "Quantity" DECIMAL(21,2),    
    "QuantityOpen" DECIMAL(21,2),
    "QuantityScan" DECIMAL(21,2),
    "UnitPriceTc" DECIMAL(21,2),
    "UomEntry" INTEGER,
    "Uom" NVARCHAR(50),
    "LineStatus" NVARCHAR(50),
    "IdPDO" INTEGER,
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_GoodsReceiptPO";
CREATE COLUMN TABLE "Tx_GoodsReceiptPO"(
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "VendorCode" NVARCHAR(50),
    "VendorName" VARCHAR(100),
    "Address" NVARCHAR(254),
    "DocEntry" BIGINT,
    "DocNum" NVARCHAR(50),
    "DocDate" TIMESTAMP,
    "RefNo" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "ApprovalStatus" NVARCHAR(50),
    "BaseEntry" BIGINT,
    "BaseDocNum" NVARCHAR(100),
    "PostingDate" TIMESTAMP,
    "IsAfterPosted" CHAR(1),
    "Comments" NVARCHAR(254),
    "CancelReason" NVARCHAR(254),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_GoodsReceiptPO_Ref";
CREATE COLUMN TABLE "Tx_GoodsReceiptPO_Ref" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "BaseId" NVARCHAR(50),
    "BaseNo" NVARCHAR(200),
    "ScanDeviceId" NVARCHAR(1000),
    "Comments" NVARCHAR(254),
    "Status" NVARCHAR(50),
    "BaseCreatedDate" TIMESTAMP,
    "BaseCreatedUser" INTEGER,
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_GoodsReceiptPO_Item";
CREATE COLUMN TABLE "Tx_GoodsReceiptPO_Item" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "WhsCode" NVARCHAR(50),
    "Quantity" DECIMAL(21,2),
    "QuantityOpen" DECIMAL(21,2),
    "QuantityScan" DECIMAL(21,2),
    "QuantityValid" DECIMAL(21,6),
    "UnitPriceTc" DECIMAL(21,2),
    "UomEntry" INTEGER,
    "Uom" NVARCHAR(50),
    "DocEntry" BIGINT,
    "DocNum" NVARCHAR(50),
    "LineNum" INTEGER,
    "BaseEntry" BIGINT,
    "BaseLine" INTEGER,
    "LineStatus" NVARCHAR(50),

    "IdPDO" INTEGER,
    "GoodsReceiptDocEntry" INTEGER,
    
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_GoodsReceiptPO_Item_Tag" ;
CREATE COLUMN TABLE "Tx_GoodsReceiptPO_Item_Tag"
(
    "Id" BIGINT,
    "DetId" BIGINT,
    "DetDetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "TagId" NVARCHAR(200),
    "Quantity" DECIMAL(21,6),
    "EventType" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "BaseId" BIGINT,
    "BaseDetId" BIGINT,
    "BaseDetDetId" BIGINT,
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_Request_StockOpname" ;
CREATE COLUMN TABLE "Tx_Request_StockOpname" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "WhsCode" NVARCHAR(50),
    "WhsName" NVARCHAR(100),
    
    "StartDate" TIMESTAMP,
    "EndDate" TIMESTAMP,
    "Description" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "CancelReason" NVARCHAR(50),

    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_StockOpname";
CREATE COLUMN TABLE "Tx_StockOpname" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "RequestId" BIGINT,
    "RequestNo" NVARCHAR(50),
    "WhsCode" NVARCHAR(50),
    "ScanDeviceId" NVARCHAR(1000),    
    "Status" NVARCHAR(50),
    "Comments" NVARCHAR(254),
    "CancelReason" NVARCHAR(500),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_StockOpname_Item";
CREATE COLUMN TABLE "Tx_StockOpname_Item" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "WhsCode" NVARCHAR(50),
    "Quantity" DECIMAL(21,2),
    "QuantityScan" DECIMAL(21,2),
    "UomEntry" INTEGER,
    "Uom" NVARCHAR(50),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_StockOpname_Item_Tag";
CREATE COLUMN TABLE "Tx_StockOpname_Item_Tag" (
    "Id" BIGINT,
    "DetId" BIGINT,
    "DetDetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "TagId" NVARCHAR(200),
    "Quantity" DECIMAL(21,6),
    "EventType" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "PostResultNote" NVARCHAR(500),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tm_ApprovalTemplate_Stage";
CREATE COLUMN TABLE "Tm_ApprovalTemplate_Stage" (
    "Id"             INTEGER,
    "DetId"          INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    "StageId"        INTEGER,
    "Step"           INTEGER,
    "SortCode"       NVARCHAR(50),
    "CreatedDate"    TIMESTAMP,
    "CreatedUser"    INTEGER,
    "ModifiedDate"   TIMESTAMP,
    "ModifiedUser"   INTEGER
);

DROP TABLE "Tx_StockSummaryOpname";
CREATE COLUMN TABLE "Tx_StockSummaryOpname"(
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    
    "DocEntry" INT,
    "DocNum" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "PostingDate" TIMESTAMP,
    "RequestId" BIGINT,
    "RequestNo" NVARCHAR(100),

    "WhsCode" NVARCHAR(50),
    "WhsName" VARCHAR(100),

    "PillarsCode" NVARCHAR(10),
    "PillarsName" NVARCHAR(50),
    "ClassCode" NVARCHAR(10),
    "ClassName" NVARCHAR(50),
    "SubClass1Code" NVARCHAR(10),
    "SubClass1Name" NVARCHAR(50),
    "SubClass2Code" NVARCHAR(10),
    "SubClass2Name" NVARCHAR(50),
    "ProjectCode" NVARCHAR(50),
    "ProjectName" NVARCHAR(100),

    "Status" NVARCHAR(50),
    "ApprovalStatus" NVARCHAR(50),
    "IsAfterPosted" CHAR(1),
    "Comments" NVARCHAR(254),
    "CancelReason" NVARCHAR(254),    

    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_StockSummaryOpname_Ref";
CREATE COLUMN TABLE "Tx_StockSummaryOpname_Ref" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "BaseId" NVARCHAR(50),
    "BaseNo" NVARCHAR(200),
    "ScanDeviceId" NVARCHAR(1000),
    "Comments" NVARCHAR(254),
    "Status" NVARCHAR(50),
    "BaseCreatedDate" TIMESTAMP,
    "BaseCreatedUser" INTEGER,
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_StockSummaryOpname_Item";
CREATE COLUMN TABLE "Tx_StockSummaryOpname_Item" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "WhsCode" NVARCHAR(50),

    "QuantityScan" DECIMAL(21,2),
    "QuantityValid" DECIMAL(21,2),	
    "QtyVariance" DECIMAL(21,2),
    "QtyOnhandSAP" DECIMAL(21,2),	
    "UnitPriceTc" DECIMAL(21,2),
    "UomEntry" INTEGER,
    "Uom" NVARCHAR(50),
    "AcctCode" NVARCHAR(100),
    "AcctName" NVARCHAR(100),

    "PillarsCode" NVARCHAR(10),
    "PillarsName" NVARCHAR(50),
    "ClassCode" NVARCHAR(10),
    "ClassName" NVARCHAR(50),
    "SubClass1Code" NVARCHAR(10),
    "SubClass1Name" NVARCHAR(50),
    "SubClass2Code" NVARCHAR(10),
    "SubClass2Name" NVARCHAR(50),
    "ProjectCode" NVARCHAR(50),
    "ProjectName" NVARCHAR(100),

    "FreeText" NVARCHAR(254),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_StockSummaryOpname_Item_Tag" ;
CREATE COLUMN TABLE "Tx_StockSummaryOpname_Item_Tag"
(
    "Id" BIGINT,
    "DetId" BIGINT,
    "DetDetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "TagId" NVARCHAR(200),
    "Quantity" DECIMAL(21,6),
    "EventType" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "BaseId" BIGINT,
    "BaseDetId" BIGINT,
    "BaseDetDetId" BIGINT,
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

ALTER TABLE "Tm_GeneralSetting"
ADD (
	"StockOpnameCoaCode" NVARCHAR(50),
	"StockOpnameCoaName" NVARCHAR(200)
)
;

DROP TABLE "Tx_TransferRequest";
CREATE TABLE "Tx_TransferRequest" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "DocEntry" BIGINT,
    "DocNum" NVARCHAR(50),
    "DocDate" TIMESTAMP,
    "VendorCode" NVARCHAR(50),
    "VendorName" VARCHAR(100),
    "Address" NVARCHAR(254),
    "FromWhsCode" NVARCHAR(50),
    "FromWhsName" VARCHAR(100),
    "ToWhsCode" NVARCHAR(50),
    "ToWhsName" VARCHAR(100),
    "PriceList" INTEGER,
    "PriceListName" NVARCHAR(50),
    "Status" NVARCHAR(50),
    "ApprovalStatus" NVARCHAR(50),
    "IsAfterPosted" CHAR(1),
    "Comments" NVARCHAR(254),
    "JournalRemarks" NVARCHAR(254),
    "CancelReason" NVARCHAR(254),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_TransferRequest_Item";
CREATE TABLE "Tx_TransferRequest_Item" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "FromWhsCode" NVARCHAR(50),
    "FromWhsName" VARCHAR(100),
    "ToWhsCode" NVARCHAR(50),
    "ToWhsName" VARCHAR(100),
    "Quantity" DECIMAL(21,2),
    "QuantityOpen" DECIMAL(21,2),
    "QuantityScan" DECIMAL(21,2),
    "LineStatus" NVARCHAR(50),
    "UomEntry" INTEGER,
    "Uom" NVARCHAR(50),
    "Comments" NVARCHAR(254),
    "FreeText" NVARCHAR(200),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);


DROP TABLE "Tx_TransferSummaryIn";
CREATE COLUMN TABLE "Tx_TransferSummaryIn" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "PostingDate" TIMESTAMP,
    "DocEntry" BIGINT,
    "DocNum" NVARCHAR(50),
    "DocDate" TIMESTAMP,
    
    "BaseId" BIGINT,
    "BaseTransNo" NVARCHAR(50),
    "BaseType" NVARCHAR(50),
    
    "VendorCode" NVARCHAR(50),
    "VendorName" VARCHAR(100),
    "Address" NVARCHAR(254),
    
    "FromWhsCode" NVARCHAR(50),
    "FromWhsName" VARCHAR(100),
    "TransitWhsCode" NVARCHAR(50),
    "TransitWhsName" NVARCHAR(100),
    "ToWhsCode" NVARCHAR(50),
    "ToWhsName" VARCHAR(100),
    
    "PriceList" INTEGER,
    "PriceListName" NVARCHAR(50),
    "Status" NVARCHAR(50),
    "ApprovalStatus" NVARCHAR(50),
    "IsAfterPosted" CHAR(1),
    "Comments" NVARCHAR(254),
    "JournalRemarks" NVARCHAR(254),
    "CancelReason" NVARCHAR(254),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_TransferSummaryIn_Item";
CREATE TABLE "Tx_TransferSummaryIn_Item" (
    "Id" INT NOT NULL,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "BaseId" BIGINT,
    "BaseDetId" INTEGER,
    "BaseType" NVARCHAR(50),
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "FromWhsCode" NVARCHAR(50),
    "FromWhsName" VARCHAR(100),
    "ToWhsCode" NVARCHAR(50),
    "ToWhsName" VARCHAR(100),
    "Quantity" DECIMAL(21,2),
    "QuantityOpen" DECIMAL(21,2),
    "QuantityScan" DECIMAL(21,2),
    "QuantityValid" DECIMAL(21,2),
    "QuantityPosted" DECIMAL(21,2),
    "UomEntry" INTEGER,
    "Uom" NVARCHAR(50),
    "Comments" NVARCHAR(254),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER,
    "TransitWhsCode" NVARCHAR(50),
    "TransitWhsName" NVARCHAR(100)
);

DROP TABLE "Tx_TransferSummaryIn_Item_tag";
CREATE TABLE "Tx_TransferSummaryIn_Item_tag" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DetId" BIGINT,
    "DetDetId" BIGINT,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "TagId" NVARCHAR(200),
    "Quantity" DECIMAL(21,6),
    "EventType" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "BaseId" BIGINT,
    "BaseDetId" BIGINT,
    "BaseDetDetId" BIGINT,
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_TransferSummaryIn_Ref";
CREATE COLUMN TABLE "Tx_TransferSummaryIn_Ref" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "BaseId" NVARCHAR(50),
    "BaseNo" NVARCHAR(200),
    "ScanDeviceId" NVARCHAR(1000),
    "Comments" NVARCHAR(254),
    "Status" NVARCHAR(50),

    "BaseCreatedDate" TIMESTAMP,
    "BaseCreatedUser" INTEGER,
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_TransferSummaryOut";
CREATE COLUMN TABLE "Tx_TransferSummaryOut" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "PostingDate" TIMESTAMP,
    "DocEntry" BIGINT,
    "DocNum" NVARCHAR(50),
    "DocDate" TIMESTAMP,
    "RequestId" BIGINT,
    "RequestNo" NVARCHAR(50),
    "BaseType" NVARCHAR(50),
    "VendorCode" NVARCHAR(50),
    "VendorName" VARCHAR(100),
    "Address" NVARCHAR(254),
    "FromWhsCode" NVARCHAR(50),
    "FromWhsName" VARCHAR(100),
    "TransitWhsCode" NVARCHAR(50),
    "TransitWhsName" NVARCHAR(100),
    "ToWhsCode" NVARCHAR(50),
    "ToWhsName" VARCHAR(100),
    "PriceList" INTEGER,
    "PriceListName" NVARCHAR(50),
    "ScanDeviceId" NVARCHAR(1000),
    "Status" NVARCHAR(50),
    "ApprovalStatus" NVARCHAR(50),
    "IsAfterPosted" CHAR(1),
    "Comments" NVARCHAR(254),
    "JournalRemarks" NVARCHAR(254),
    "CancelReason" NVARCHAR(254),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_TransferSummaryOut_Item";
CREATE COLUMN TABLE "Tx_TransferSummaryOut_Item"
(
    "Id"               BIGINT,
    "DetId"            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "RequestId"           BIGINT,
    "RequestDetId"        BIGINT,
    "BaseType"         NVARCHAR(50),
    "ItemCode"         NVARCHAR(50),
    "ItemName"         NVARCHAR(200),
    "FromWhsCode"      NVARCHAR(50),
    "FromWhsName"      VARCHAR(100),
    "TransitWhsCode"   NVARCHAR(50),
    "TransitWhsName"   NVARCHAR(100),
    "ToWhsCode"        NVARCHAR(50),
    "ToWhsName"        VARCHAR(100),
    "QuantityRequest"         DECIMAL(21,2),
    "QuantityScan"     DECIMAL(21,2),
    "QuantityValid"     DECIMAL(21,2),
    "QuantityPosted"     DECIMAL(21,2),
    "QuantityToReceipt" DECIMAL(21,2),
    "LineStatus" NVARCHAR(50),
    "UomEntry"         INTEGER,
    "Uom"              NVARCHAR(50),
    "Comments"         NVARCHAR(254),
    "CreatedDate"      TIMESTAMP,
    "CreatedUser"      INTEGER,
    "ModifiedDate"     TIMESTAMP,
    "ModifiedUser"     INTEGER

);

DROP TABLE "Tx_TransferSummaryOut_Item_Tag";
CREATE COLUMN TABLE "Tx_TransferSummaryOut_Item_Tag"
(
    "Id"            BIGINT,
    "DetId"         BIGINT,
    "DetDetId"      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "ItemCode"      NVARCHAR(50),
    "ItemName"      NVARCHAR(200),
    "TagId"         NVARCHAR(200),
    "Quantity"      DECIMAL(21,6),
    "EventType"     NVARCHAR(100),
    "Status"        NVARCHAR(50),
    "BaseId"        BIGINT,
    "BaseDetId"     BIGINT,
    "BaseDetDetId"  BIGINT,
    "CreatedDate"   TIMESTAMP,
    "CreatedUser"   INTEGER,
    "ModifiedDate"  TIMESTAMP,
    "ModifiedUser"  INTEGER
);

DROP TABLE "Tx_TransferSummaryOut_Ref";
CREATE COLUMN TABLE "Tx_TransferSummaryOut_Ref" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "BaseId" NVARCHAR(50),
    "BaseNo" NVARCHAR(200),
    "ScanDeviceId" NVARCHAR(1000),
    "Comments" NVARCHAR(254),
    "Status" NVARCHAR(50),

    "BaseCreatedDate" TIMESTAMP,
    "BaseCreatedUser" INTEGER,
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tm_Item_Warehouse_Tag_Replace";
CREATE COLUMN TABLE "Tm_Item_Warehouse_Tag_Replace" (
    "TagId" NVARCHAR(200) NOT NULL,
    "ItemCode" NVARCHAR(50) NOT NULL,
    "ItemName" NVARCHAR(200),
    "WhsCode" NVARCHAR(50),
    "WhsName" NVARCHAR(200),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER,
    PRIMARY KEY ("TagId", "ItemCode")
);

DROP TABLE "Tm_Item_Warehouse_Tag_Log";
CREATE COLUMN TABLE "Tm_Item_Warehouse_Tag_Log"
(
    "LogId" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "BaseType" NVARCHAR(50) ,
    "ItemCode" NVARCHAR(50) NOT NULL,
    "ItemName" NVARCHAR(200),
    "WhsCode" NVARCHAR(50),
    "WhsName" NVARCHAR(200),
    "TagId" NVARCHAR(200),
    "Status"  NVARCHAR(200),
    "Event" NVARCHAR(100),
    "ActionNote" NVARCHAR(500),
    "CreatedDate" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "CreatedUser" INTEGER,
    PRIMARY KEY ("LogId")
);

DROP TABLE "Tx_DeactiveTag_Log";
CREATE COLUMN TABLE "Tx_DeactiveTag_Log"
(
    "LogId" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    "TagId" NVARCHAR(200),    
    "ItemCode" NVARCHAR(50) NOT NULL,
    "ItemName" NVARCHAR(200),
    "WhsCode" NVARCHAR(50),
    "WhsName" NVARCHAR(200),
    "Message" NVARCHAR(5000),
    "CreatedDate" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "CreatedUser" INTEGER,
    PRIMARY KEY ("LogId")
);

DROP TABLE "Tx_DeactiveTag";
CREATE COLUMN TABLE "Tx_DeactiveTag" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "ScanDeviceId" NVARCHAR(1000),
    "TransDate" TIMESTAMP,
    "PostingDate" TIMESTAMP,
    "Status" NVARCHAR(50),

    "Remarks" NVARCHAR(200),
    "CancelReason" NVARCHAR(500),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_DeactiveTag_Item";
CREATE COLUMN TABLE "Tx_DeactiveTag_Item" (
    "Id" BIGINT NOT NULL,
    "TagId" NVARCHAR(200) NOT NULL PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "FreeText" NVARCHAR(1000),
    "WhsCode" NVARCHAR(50),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);
