DROP TABLE "Tx_AdjustmentIn";
CREATE COLUMN TABLE "Tx_AdjustmentIn" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "AdjustmentTypeCode" NVARCHAR(100),
    "AdjustmentTypeName" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "IsAfterPosted" CHAR(1),
    "DocEntry" INTEGER,
    "Comments" NVARCHAR(200),
    "ScanDeviceId" NVARCHAR(1000),
    "WhsCode" NVARCHAR(50),
    "CancelReason" NVARCHAR(500),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);


DROP TABLE "Tx_AdjustmentIn_Item";
CREATE COLUMN TABLE "Tx_AdjustmentIn_Item" (
    "Id" BIGINT NOT NULL,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "FreeText" NVARCHAR(1000),
    "WhsCode" NVARCHAR(50),
    "QuantityScan" DECIMAL(21, 2), 
    "QuantityPosted" DECIMAL(21, 2), 
    "LineStatus" NVARCHAR(50),
    "UnitPriceTc" DECIMAL(21, 2),  
    "UomEntry" INT,
    "Uom" NVARCHAR(50),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_AdjustmentIn_Item_Tag";
CREATE COLUMN TABLE "Tx_AdjustmentIn_Item_Tag" (
    "Id" BIGINT,
    "DetId" BIGINT,
    "DetDetId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "TagId" NVARCHAR(200),
    "Quantity" DECIMAL(21,6),
    "EventType" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "PostResultNote" NVARCHAR(500),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_AdjustmentOut";
CREATE COLUMN TABLE "Tx_AdjustmentOut" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "AdjustmentTypeCode" NVARCHAR(100),
    "AdjustmentTypeName" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "IsAfterPosted" CHAR(1),
    "DocEntry" INTEGER,
    "Comments" NVARCHAR(200),
    "ScanDeviceId" NVARCHAR(1000),
    "WhsCode" NVARCHAR(50),
    "CancelReason" NVARCHAR(500),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_AdjustmentOut_Item";
CREATE COLUMN TABLE "Tx_AdjustmentOut_Item" (
    "Id" BIGINT NOT NULL,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "FreeText" NVARCHAR(1000),
    "WhsCode" NVARCHAR(50),
    "QuantityScan" DECIMAL(21, 2),
    "QuantityPosted" DECIMAL(21, 2), 
    "LineStatus" NVARCHAR(50),
    "UomEntry" INT,
    "Uom" NVARCHAR(50),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_AdjustmentOut_Item_Tag";
CREATE COLUMN TABLE "Tx_AdjustmentOut_Item_Tag" (
    "Id" BIGINT,
    "DetId" BIGINT,
    "DetDetId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "TagId" NVARCHAR(200),
    "Quantity" DECIMAL(21,6),
    "EventType" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "PostResultNote" NVARCHAR(500),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_PurchaseOrder";
CREATE COLUMN TABLE ""Tx_PurchaseOrder" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "VendorCode" NVARCHAR(50),
    "VendorName" VARCHAR(100),
    "Address" NVARCHAR(254),
    "DocEntry" BIGINT,
    "DocNum" NVARCHAR(50),
    "DocDate" TIMESTAMP,
    "RefNo" NVARCHAR(100),
    "ScanDeviceId" NVARCHAR(1000),
    "Status" NVARCHAR(50),
    "IsAfterPosted" CHAR(1),
    "Comments" NVARCHAR(254),
    "CancelReason" NVARCHAR(254),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER,
    PRIMARY KEY ("Id")
);

DROP TABLE "Tx_PurchaseOrder_Item";
CREATE COLUMN TABLE "Tx_PurchaseOrder_Item" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "DocEntry" BIGINT,
    "DocNum" NVARCHAR(50),
    "BaseLine" INTEGER,
    "LineNum" INTEGER,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "WhsCode" NVARCHAR(50),
    "Quantity" DECIMAL(21,2),    
    "QuantityOpen" DECIMAL(21,2),
    "QuantityScan" DECIMAL(21,2),
    "UnitPriceTc" DECIMAL(21,2),
    "UomEntry" INTEGER,
    "Uom" NVARCHAR(50),
    "LineStatus" NVARCHAR(50),
    "IdPDO" INTEGER,
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_GoodsReceiptPO";
CREATE COLUMN TABLE "Tx_GoodsReceiptPO"(
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "VendorCode" NVARCHAR(50),
    "VendorName" VARCHAR(100),
    "Address" NVARCHAR(254),
    "DocEntry" BIGINT,
    "DocNum" NVARCHAR(50),
    "DocDate" TIMESTAMP,
    "RefNo" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "ApprovalStatus" NVARCHAR(50),
    "BaseEntry" BIGINT,
    "BaseDocNum" NVARCHAR(100),
    "PostingDate" TIMESTAMP,
    "IsAfterPosted" CHAR(1),
    "Comments" NVARCHAR(254),
    "CancelReason" NVARCHAR(254),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_GoodsReceiptPO_Ref";
CREATE COLUMN TABLE "Tx_GoodsReceiptPO_Ref" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "BaseId" NVARCHAR(50),
    "BaseNo" NVARCHAR(200),
    "ScanDeviceId" NVARCHAR(1000),
    "Comments" NVARCHAR(254),
    
    "BaseCreatedDate" TIMESTAMP,
    "BaseCreatedUser" INTEGER,
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_GoodsReceiptPO_Item";
CREATE COLUMN TABLE "Tx_GoodsReceiptPO_Item" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "WhsCode" NVARCHAR(50),
    "Quantity" DECIMAL(21,2),
    "QuantityOpen" DECIMAL(21,2),
    "QuantityScan" DECIMAL(21,2),
    "QuantityValid" DECIMAL(21,6),
    "UnitPriceTc" DECIMAL(21,2),
    "UomEntry" INTEGER,
    "Uom" NVARCHAR(50),
    "DocEntry" BIGINT,
    "DocNum" NVARCHAR(50),
    "LineNum" INTEGER,
    "BaseEntry" BIGINT,
    "BaseLine" INTEGER,
    "LineStatus" NVARCHAR(50),

    "IdPDO" INTEGER,
    "GoodsReceiptDocEntry" INTEGER,
    
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_GoodsReceiptPO_Item_Tag" ;
CREATE COLUMN TABLE "Tx_GoodsReceiptPO_Item_Tag"
(
    "Id" BIGINT,
    "DetId" BIGINT,
    "DetDetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "TagId" NVARCHAR(200),
    "Quantity" DECIMAL(21,6),
    "EventType" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "BaseId" BIGINT,
    "BaseDetId" BIGINT,
    "BaseDetDetId" BIGINT,
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_Request_StockOpname" ;
CREATE COLUMN TABLE "Tx_Request_StockOpname" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "WhsCode" NVARCHAR(50),
    "WhsName" NVARCHAR(100),
    
    "StartDate" TIMESTAMP,
    "EndDate" TIMESTAMP,
    "Description" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "CancelReason" NVARCHAR(50),

    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_StockOpname";
CREATE COLUMN TABLE "Tx_StockOpname" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "RequestId" BIGINT,
    "RequestNo" NVARCHAR(50),
    "WhsCode" NVARCHAR(50),
    "ScanDeviceId" NVARCHAR(1000),    
    "Status" NVARCHAR(50),
    "Comments" NVARCHAR(254),
    "CancelReason" NVARCHAR(500),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_StockOpname_Item";
CREATE COLUMN TABLE "Tx_StockOpname_Item" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "WhsCode" NVARCHAR(50),
    "Quantity" DECIMAL(21,2),
    "QuantityScan" DECIMAL(21,2),
    "UomEntry" INTEGER,
    "Uom" NVARCHAR(50),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_StockOpname_Item_Tag";
CREATE COLUMN TABLE "Tx_StockOpname_Item_Tag" (
    "Id" BIGINT,
    "DetId" BIGINT,
    "DetDetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "TagId" NVARCHAR(200),
    "Quantity" DECIMAL(21,6),
    "EventType" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "PostResultNote" NVARCHAR(500),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tm_ApprovalTemplate_Stage";
CREATE COLUMN TABLE "Tm_ApprovalTemplate_Stage" (
    "Id"             INTEGER,
    "DetId"          INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    "StageId"        INTEGER,
    "Step"           INTEGER,
    "SortCode"       NVARCHAR(50),
    "CreatedDate"    TIMESTAMP,
    "CreatedUser"    INTEGER,
    "ModifiedDate"   TIMESTAMP,
    "ModifiedUser"   INTEGER
);

DROP TABLE "Tx_StockSummaryOpname";
CREATE COLUMN TABLE "Tx_StockSummaryOpname"(
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    
    "DocEntry" INT,
    
    "TransDate" TIMESTAMP,
    "RequestId" BIGINT,
    "RequestNo" NVARCHAR(100),

    "WhsCode" NVARCHAR(50),
    "WhsName" VARCHAR(100),

    "Status" NVARCHAR(50),
    "ApprovalStatus" NVARCHAR(50),
    "IsAfterPosted" CHAR(1),
    "Comments" NVARCHAR(254),
    "CancelReason" NVARCHAR(254),    

    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_StockSummaryOpname_Ref";
CREATE COLUMN TABLE "Tx_StockSummaryOpname_Ref" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "BaseId" NVARCHAR(50),
    "BaseNo" NVARCHAR(200),
    "ScanDeviceId" NVARCHAR(1000),
    "Comments" NVARCHAR(254),
    
    "BaseCreatedDate" TIMESTAMP,
    "BaseCreatedUser" INTEGER,
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_StockSummaryOpname_Item";
CREATE COLUMN TABLE "Tx_StockSummaryOpname_Item" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "WhsCode" NVARCHAR(50),

    "QuantityScan" DECIMAL(21,2),
    "QuantityValid" DECIMAL(21,2),	
    "UnitPriceTc" DECIMAL(21,2),
    "UomEntry" INTEGER,
    "Uom" NVARCHAR(50),
    "AcctCode" NVARCHAR(100),
    "AcctName" NVARCHAR(100),

    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_StockSummaryOpname_Item_Tag" ;
CREATE COLUMN TABLE "Tx_StockSummaryOpname_Item_Tag"
(
    "Id" BIGINT,
    "DetId" BIGINT,
    "DetDetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "TagId" NVARCHAR(200),
    "Quantity" DECIMAL(21,6),
    "EventType" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "BaseId" BIGINT,
    "BaseDetId" BIGINT,
    "BaseDetDetId" BIGINT,
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

ALTER TABLE "Tm_GeneralSetting"
ADD (
	"StockOpnameCoaCode" NVARCHAR(50),
	"StockOpnameCoaName" NVARCHAR(200)
)
;