DROP TABLE "Tx_AdjustmentIn";
CREATE COLUMN TABLE "Tx_AdjustmentIn" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "AdjustmentTypeCode" NVARCHAR(100),
    "AdjustmentTypeName" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "IsAfterPosted" CHAR(1),
    "DocEntry" INTEGER,
    "Comments" NVARCHAR(200),
    "ScanDeviceId" NVARCHAR(1000),
    "WhsCode" NVARCHAR(50),
    "CancelReason" NVARCHAR(500),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);


DROP TABLE "Tx_AdjustmentIn_Item";
CREATE COLUMN TABLE "Tx_AdjustmentIn_Item" (
    "Id" BIGINT NOT NULL,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "FreeText" NVARCHAR(1000),
    "WhsCode" NVARCHAR(50),
    "QuantityScan" DECIMAL(21, 2),    
    "LineStatus" NVARCHAR(50),
    "UomEntry" INT,
    "Uom" NVARCHAR(50),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_AdjustmentIn_Item_Tag";
CREATE COLUMN TABLE "Tx_AdjustmentIn_Item_Tag" (
    "Id" BIGINT,
    "DetId" BIGINT,
    "DetDetId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "TagId" NVARCHAR(200),
    "Quantity" DECIMAL(21,6),
    "EventType" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);


DROP TABLE "Tx_AdjustmentOut";
CREATE COLUMN TABLE "Tx_AdjustmentOut" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TransType" NVARCHAR(50),
    "TransNo" NVARCHAR(50),
    "TransDate" TIMESTAMP,
    "AdjustmentTypeCode" NVARCHAR(100),
    "AdjustmentTypeName" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "IsAfterPosted" CHAR(1),
    "DocEntry" INTEGER,
    "Comments" NVARCHAR(200),
    "ScanDeviceId" NVARCHAR(1000),
    "WhsCode" NVARCHAR(50),
    "CancelReason" NVARCHAR(500),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_AdjustmentOut_Item";
CREATE COLUMN TABLE "Tx_AdjustmentOut_Item" (
    "Id" BIGINT NOT NULL,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "FreeText" NVARCHAR(1000),
    "WhsCode" NVARCHAR(50),
    "QuantityScan" DECIMAL(21, 2),    
    "LineStatus" NVARCHAR(50),
    "UomEntry" INT,
    "Uom" NVARCHAR(50),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_AdjustmentOut_Item_Tag";
CREATE COLUMN TABLE "Tx_AdjustmentOut_Item_Tag" (
    "Id" BIGINT,
    "DetId" BIGINT,
    "DetDetId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "TagId" NVARCHAR(200),
    "Quantity" DECIMAL(21,6),
    "EventType" NVARCHAR(100),
    "Status" NVARCHAR(50),
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_PurchaseOrder_Item";
CREATE COLUMN TABLE "Tx_PurchaseOrder_Item" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "DocEntry" BIGINT,
    "DocNum" NVARCHAR(50),
    "BaseLine" INTEGER,
    "LineNum" INTEGER,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "WhsCode" NVARCHAR(50),
    "Quantity" DECIMAL(21,2),    
    "QuantityOpen" DECIMAL(21,2),
    "QuantityScan" DECIMAL(21,2),
    "UnitPriceTc" DECIMAL(21,2),
    "UomEntry" INTEGER,
    "Uom" NVARCHAR(50),
    "LineStatus" NVARCHAR(50),
    "IdPDO" INTEGER,
    
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);

DROP TABLE "Tx_GoodsReceiptPO_Item";
CREATE COLUMN TABLE "Tx_GoodsReceiptPO_Item" (
    "Id" BIGINT,
    "DetId" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "ItemCode" NVARCHAR(50),
    "ItemName" NVARCHAR(200),
    "WhsCode" NVARCHAR(50),
    "Quantity" DECIMAL(21,2),
    "QuantityOpen" DECIMAL(21,2),
    "QuantityScan" DECIMAL(21,2),
    "UnitPriceTc" DECIMAL(21,2),
    "UomEntry" INTEGER,
    "Uom" NVARCHAR(50),
    "DocEntry" BIGINT,
    "DocNum" NVARCHAR(50),
    "LineNum" INTEGER,
    "BaseEntry" BIGINT,
    "BaseLine" INTEGER,
    "LineStatus" NVARCHAR(50),

    "IdPDO" INTEGER,
    "GoodsReceiptDocEntry" INTEGER,
    
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
);