

DROP TABLE "Tm_VehicleType";
CREATE TABLE "Tm_VehicleType"(
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
    "TypeName" NVARCHAR(200),
    "Remarks" NVARCHAR(200),
    "IsActive" CHAR(1),

    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
)
;

DROP TABLE "Tm_Vehicle";
CREATE COLUMN TABLE "Tm_Vehicle" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TransType" NVARCHAR(50),
    
    "VehicleNo" NVARCHAR(50),	
    "VehicleName" NVARCHAR(50),
    "VehicleType" INT,

    "WhsCode" NVARCHAR(50),
    "WhsName" NVARCHAR(100),    

    "Remarks" NVARCHAR(200),    
    "IsActive" NVARCHAR(10),
    
    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
    
);

DROP TABLE "Tm_Driver" ;
CREATE COLUMN TABLE "Tm_Driver" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
    "TransType" NVARCHAR(50),
    
    "FirstName" NVARCHAR(100),
    "LastName" NVARCHAR(100),
    
    "Address" NVARCHAR(1000),
    "Handphone" NVARCHAR(50),
    "IdCardNo" NVARCHAR(50),
    "DrivingLicenceNo" NVARCHAR(50),

    "Remarks" NVARCHAR(200),
    "IsActive" CHAR(1),

    "CreatedDate" TIMESTAMP,
    "CreatedUser" INTEGER,
    "ModifiedDate" TIMESTAMP,
    "ModifiedUser" INTEGER
    
);